version: '3'

services:
  outbound-mysql:
    container_name: outbound-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
  outbound-api:
    container_name: outbound-api
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8081:8080"
    depends_on:
      - outbound-mysql
    tty: true